"""Bifrost render — emit the roadmap back out of the database.

The document is a VIEW now. It is regenerated, committed so GitHub rendering and
diff review still work, and a PreToolUse hook redirects hand-edits to the
database.

Determinism is a hard requirement rather than a nicety. A renderer that emits a
timestamp, or orders anything by a database rowid that shifts when a row is
rewritten, produces a thousand-line diff on every regeneration -- and an
unreviewable diff defeats the entire reason for committing the file. So:

  * ordering is by migration_para.ordinal, which is the document's own order
  * no timestamps, no run ids, no "generated at"
  * the only volatile thing named is the source commit, which is a fact about
    the input rather than about this run

`render_twice_identical()` is the test, and it is run by the test suite.
"""

from __future__ import annotations

import json
import sqlite3
from pathlib import Path

from . import core

HEADER = """<!-- GENERATED FROM BIFROST. Do not edit this file by hand.

     This document is OUTPUT, not input. It exists so a person can read the
     project's state on GitHub, in review, or away from a terminal. It is not the
     agent-facing copy of anything: an agent should query the database, where the
     same answer costs hundreds of tokens instead of tens of thousands.

     Every assertion below is a row in build/bifrost.db. Edit the row, not the
     document:

         python -m bifrost realm <format>      read what is known
         python -m bifrost digest              whole-project state
         python -m bifrost render              regenerate this file

     Status in the margin is DERIVED from gate runs and discriminators, never
     typed: an agent may assert 'verified' and the database will still print
     'asserted-unbacked' until a passing gate invariant or a discriminator backs
     it. See tools/bifrost/README.md.
-->

"""

# Only these get a margin marker. A plain verified claim reads as prose, which
# is what the document is for; the markers exist to make the exceptions
# impossible to skim past.
MARKERS = {
    "refuted": "**[REFUTED]** ",
    "asserted-unbacked": "**[UNBACKED]** ",
    "assumed": "**[ASSUMED]** ",
    "plausible": "",
    "verified": "",
}


def _citation_line(conn: sqlite3.Connection, claim_id: int) -> str:
    """Render a claim's evidence compactly, resolving symbols where they exist."""
    rows = core.rows(conn, """
        SELECT s.kind, s.locator, s.symbol, s.containing_symbol, s.offset_in_symbol
        FROM citation ct JOIN source s ON s.id = ct.source_id
        WHERE ct.claim_id = ?
        ORDER BY s.kind, s.locator""", (claim_id,))
    if not rows:
        return ""

    # A paragraph that names a function both by address and in backticks yields
    # two tokens -- disasm_fn 0x82637a98 and map_symbol animDefGetAnimChannelData
    # -- and both are real evidence worth storing. Printing both is redundant, so
    # the bare symbol is dropped when an address already resolved to it. The
    # CITATION rows are untouched; only the rendering is deduplicated.
    resolved = {r["symbol"] for r in rows if r["symbol"]}
    resolved |= {r["containing_symbol"] for r in rows if r["containing_symbol"]}

    parts, seen = [], set()
    for r in rows:
        if r["kind"] == "map_symbol" and r["locator"] in resolved:
            continue
        if r["symbol"]:
            s = f"`{r['symbol']}` ({r['locator']})"
        elif r["containing_symbol"]:
            s = f"`{r['containing_symbol']}`+0x{r['offset_in_symbol']:x} ({r['locator']})"
        elif r["kind"] == "measurement":
            s = r["locator"]
        else:
            s = f"`{r['locator']}`"
        if s not in seen:
            seen.add(s)
            parts.append(s)
    return "<sub>Cited: " + " &middot; ".join(parts) + "</sub>" if parts else ""


def render(conn: sqlite3.Connection, source_path: str | None = None) -> str:
    src = core.one(
        conn,
        "SELECT * FROM migration_source WHERE path = ? ORDER BY id DESC LIMIT 1"
        if source_path else
        "SELECT * FROM migration_source ORDER BY id DESC LIMIT 1",
        (source_path,) if source_path else ())
    if not src:
        raise core.BifrostError("no migrated document to render")

    out: list[str] = [HEADER.rstrip("\n"), ""]

    for para in core.rows(conn, """
            SELECT id, ordinal, text, accounted_kind
            FROM migration_para WHERE migration_source_id = ?
            ORDER BY ordinal""", (src["id"],)):

        kind = para["accounted_kind"]

        if kind in ("heading", "rule", "passage"):
            out.append(para["text"])
            out.append("")
            continue

        if kind == "claim":
            claims = core.rows(conn, """
                SELECT s.id, s.statement, s.effective_status
                FROM v_claim_status s
                JOIN claim c ON c.id = s.id
                WHERE c.para_id = ?
                ORDER BY s.id""", (para["id"],))
            for c in claims:
                out.append(MARKERS.get(c["effective_status"], "") + c["statement"])
                cites = _citation_line(conn, c["id"])
                if cites:
                    out.append("")
                    out.append(cites)
                for r in core.rows(conn, """
                        SELECT why_plausible, what_killed_it FROM refutation
                        WHERE refuted_claim = ? ORDER BY id""", (c["id"],)):
                    out.append("")
                    out.append(f"> **Refuted.** {r['what_killed_it']}")
                    if r["why_plausible"]:
                        out.append(f">")
                        out.append(f"> *It was plausible because:* {r['why_plausible']}")
                for d in core.rows(conn, """
                        SELECT check_desc, result_a, result_b, separation
                        FROM discriminator WHERE claim_a = ? ORDER BY id""", (c["id"],)):
                    out.append("")
                    out.append(f"> **Discriminator.** {d['check_desc']} &mdash; "
                               f"{d['result_a']} against {d['result_b']}"
                               + (f" ({d['separation']})" if d["separation"] else ""))
                out.append("")
            continue

        # anything else was accounted but has no renderer: keep the original
        # rather than dropping it, because losing content silently is the one
        # failure this migration must not have.
        out.append(para["text"])
        out.append("")

    text = "\n".join(out).rstrip("\n") + "\n"
    return text


def render_to_file(conn: sqlite3.Connection, path: Path | None = None) -> dict:
    src = core.one(conn, "SELECT * FROM migration_source ORDER BY id DESC LIMIT 1")
    p = Path(path) if path else (core.repo_root() / src["path"])
    text = render(conn)
    before = p.read_text(encoding="utf-8") if p.exists() else None
    p.write_text(text, encoding="utf-8")
    return {"path": str(p).replace("\\", "/"), "bytes": len(text.encode("utf-8")),
            "lines": text.count("\n"), "changed": before != text,
            "source_commit": src["commit_sha"], "source_path": src["path"]}


def render_twice_identical(conn: sqlite3.Connection) -> bool:
    """The determinism test. A renderer that is not deterministic makes the
    committed artefact unreviewable, which defeats committing it."""
    return render(conn) == render(conn)
